import os
from datetime import datetime, timezone
from flask import Flask, jsonify, request, send_from_directory
from sqlalchemy import create_engine, text

app = Flask(__name__)

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATABASE_URL = os.environ.get("DATABASE_URL", "sqlite:///baixas.db")

# Render/Postgres sometimes provides postgres://; SQLAlchemy expects postgresql://
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL, pool_pre_ping=True)

def init_db():
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS atualizacoes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                descricao TEXT,
                total_clientes INTEGER NOT NULL DEFAULT 0,
                total_valor NUMERIC(18,2) NOT NULL DEFAULT 0,
                total_credito NUMERIC(18,2) NOT NULL DEFAULT 0
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS atualizacao_itens (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                atualizacao_id INTEGER NOT NULL REFERENCES atualizacoes(id) ON DELETE CASCADE,
                codigo TEXT,
                valor NUMERIC(18,2) NOT NULL DEFAULT 0,
                credito NUMERIC(18,2) NOT NULL DEFAULT 0,
                saldo NUMERIC(18,2) NOT NULL DEFAULT 0,
                base TEXT
            )
        """))
        conn.execute(text("""
            CREATE INDEX IF NOT EXISTS idx_atualizacao_itens_atualizacao
            ON atualizacao_itens(atualizacao_id)
        """))

def init_sqlite():
    with engine.begin() as conn:
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS atualizacoes (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                criado_em TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                descricao TEXT,
                total_clientes INTEGER NOT NULL DEFAULT 0,
                total_valor REAL NOT NULL DEFAULT 0,
                total_credito REAL NOT NULL DEFAULT 0
            )
        """))
        conn.execute(text("""
            CREATE TABLE IF NOT EXISTS atualizacao_itens (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                atualizacao_id INTEGER NOT NULL,
                codigo TEXT,
                valor REAL NOT NULL DEFAULT 0,
                credito REAL NOT NULL DEFAULT 0,
                saldo REAL NOT NULL DEFAULT 0,
                base TEXT,
                FOREIGN KEY(atualizacao_id) REFERENCES atualizacoes(id) ON DELETE CASCADE
            )
        """))

try:
    if DATABASE_URL.startswith("sqlite"):
        init_sqlite()
    else:
        init_db()
except Exception as e:
    print("ERRO AO INICIALIZAR BANCO:", repr(e), flush=True)
    raise

@app.get("/")
def home():
    return send_from_directory(BASE_DIR, "index_v10.html")

@app.get("/health")
def health():
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return jsonify(ok=True, sistema="Mestre Marceneiro - Sistema de Baixas", banco="conectado")
    except Exception as e:
        return jsonify(ok=False, erro=str(e)), 500

def serializa_atualizacao(row):
    criado = row.criado_em
    if hasattr(criado, "isoformat"):
        criado = criado.isoformat()
    return {
        "id": row.id,
        "criado_em": str(criado),
        "descricao": row.descricao or "",
        "total_clientes": int(row.total_clientes or 0),
        "total_valor": float(row.total_valor or 0),
        "total_credito": float(row.total_credito or 0),
    }

@app.get("/api/atualizacoes")
def listar_atualizacoes():
    with engine.connect() as conn:
        rows = conn.execute(text("""
            SELECT id, criado_em, descricao, total_clientes, total_valor, total_credito
            FROM atualizacoes
            ORDER BY id DESC
            LIMIT 100
        """)).fetchall()
    return jsonify([serializa_atualizacao(r) for r in rows])

@app.post("/api/atualizacoes")
def gravar_atualizacao():
    payload = request.get_json(silent=True) or {}
    itens = payload.get("itens") or []
    descricao = (payload.get("descricao") or "Atualização diária").strip()

    if not isinstance(itens, list) or not itens:
        return jsonify(erro="Nenhum item recebido para gravação."), 400

    total_valor = sum(float(x.get("valor") or 0) for x in itens)
    total_credito = sum(float(x.get("credito") or 0) for x in itens)

    with engine.begin() as conn:
        if DATABASE_URL.startswith("sqlite"):
            res = conn.execute(text("""
                INSERT INTO atualizacoes
                (criado_em, descricao, total_clientes, total_valor, total_credito)
                VALUES (:criado_em, :descricao, :total_clientes, :total_valor, :total_credito)
            """), {
                "criado_em": datetime.now(timezone.utc).isoformat(),
                "descricao": descricao,
                "total_clientes": len(itens),
                "total_valor": total_valor,
                "total_credito": total_credito,
            })
            atualizacao_id = res.lastrowid
        else:
            atualizacao_id = conn.execute(text("""
                INSERT INTO atualizacoes
                (descricao, total_clientes, total_valor, total_credito)
                VALUES (:descricao, :total_clientes, :total_valor, :total_credito)
                RETURNING id
            """), {
                "descricao": descricao,
                "total_clientes": len(itens),
                "total_valor": total_valor,
                "total_credito": total_credito,
            }).scalar_one()

        conn.execute(text("""
            INSERT INTO atualizacao_itens
            (atualizacao_id, codigo, valor, credito, saldo, base)
            VALUES (:atualizacao_id, :codigo, :valor, :credito, :saldo, :base)
        """), [{
            "atualizacao_id": atualizacao_id,
            "codigo": str(x.get("codigo") or ""),
            "valor": float(x.get("valor") or 0),
            "credito": float(x.get("credito") or 0),
            "saldo": float(x.get("saldo") or 0),
            "base": str(x.get("base") or ""),
        } for x in itens])

    return jsonify(ok=True, id=atualizacao_id)

def carregar_atualizacao(atualizacao_id):
    with engine.connect() as conn:
        a = conn.execute(text("""
            SELECT id, criado_em, descricao, total_clientes, total_valor, total_credito
            FROM atualizacoes WHERE id=:id
        """), {"id": atualizacao_id}).fetchone()
        if not a:
            return None
        itens = conn.execute(text("""
            SELECT codigo, valor, credito, saldo, base
            FROM atualizacao_itens
            WHERE atualizacao_id=:id
            ORDER BY base, saldo, codigo
        """), {"id": atualizacao_id}).fetchall()

    return {
        "atualizacao": serializa_atualizacao(a),
        "itens": [{
            "codigo": r.codigo or "",
            "valor": float(r.valor or 0),
            "credito": float(r.credito or 0),
            "saldo": float(r.saldo or 0),
            "base": r.base or "",
        } for r in itens]
    }

@app.get("/api/atual")
def abrir_atual():
    with engine.connect() as conn:
        atualizacao_id = conn.execute(text(
            "SELECT id FROM atualizacoes ORDER BY id DESC LIMIT 1"
        )).scalar()
    if not atualizacao_id:
        return jsonify(atualizacao=None, itens=[])
    return jsonify(carregar_atualizacao(atualizacao_id))

@app.get("/api/atualizacoes/<int:atualizacao_id>")
def abrir_atualizacao(atualizacao_id):
    dados = carregar_atualizacao(atualizacao_id)
    if not dados:
        return jsonify(erro="Atualização não encontrada."), 404
    return jsonify(dados)

if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))
    app.run(host="0.0.0.0", port=port)
